# Generated by Django 2.0.9 on 2018-12-04 13:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='код')),
                ('format', models.CharField(choices=[('xlsx', 'XLSX'), ('xls', 'XLS'), ('csv', 'CSV')], default='xlsx', max_length=5, verbose_name='формат')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='модель')),
                ('queryset', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True, verbose_name='queryset')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True, verbose_name='параметры')),
            ],
            options={
                'verbose_name': 'Шаблон отчета',
                'verbose_name_plural': 'Шаблоны отчетов',
            },
        ),
    ]
