# Generated by Django 2.0.5 on 2018-12-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xlsexport', '0002_exporttemplate_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
            ],
            options={
                'verbose_name': 'Импорт из XLSX/XLS',
                'verbose_name_plural': 'Импорт из XLSX/XLS',
                'proxy': True,
                'indexes': [],
            },
            bases=('xlsexport.exporttemplate',),
        ),
    ]
