# Generated by Django 3.1.6 on 2021-02-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlsexport', '0004_alter_field_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporttemplate',
            name='params',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='параметры'),
        ),
        migrations.AlterField(
            model_name='exporttemplate',
            name='queryset',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='queryset'),
        ),
    ]
