# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientrecord',
            options={'verbose_name': 'Клиентская ошибка', 'verbose_name_plural': 'Журнал клиентских ошибок'},
        ),
        migrations.AlterModelOptions(
            name='serverrecord',
            options={'verbose_name': 'Системная ошибка', 'verbose_name_plural': 'Журнал системных ошибок'},
        ),
    ]
