# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 18:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applogs', '0002_auto_20170209_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverrecord',
            name='name',
        ),
        migrations.AddField(
            model_name='serverrecord',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True, verbose_name='доп. информация'),
        ),
    ]
