# Generated by Django 2.0.5 on 2018-07-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applogs', '0004_auto_20170606_2139'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX applogs_serverrecord__level__index ON applogs_serverrecord (level)",
            "DROP INDEX applogs_serverrecord__level__index"
        ),
        migrations.RunSQL(
            "CREATE INDEX applogs_serverrecord__params_method__index ON applogs_serverrecord ((params->>'method'))",
            "DROP INDEX applogs_serverrecord__params_method__index"
        ),
        migrations.RunSQL(
            "CREATE INDEX applogs_serverrecord__params_source__index ON applogs_serverrecord ((params->>'source'))",
            "DROP INDEX applogs_serverrecord__params_source__index"
        ),
    ]
