# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-16 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogs', '0007_serverrecord_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrecord',
            name='duration',
            field=models.FloatField(default=0.0, verbose_name='продолжительность'),
        ),
        migrations.AddField(
            model_name='serverrecord',
            name='method',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='метод'),
        ),
    ]
