# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-16 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogs', '0008_auto_20180816_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverrecord',
            name='level',
            field=models.CharField(choices=[('INFO', 'INFO'), ('ERROR', 'ERROR'), ('DEBUG', 'DEBUG')], default='INFO', max_length=5, verbose_name='важность'),
        ),
    ]
