# Generated by Django 2.0.3 on 2018-11-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogs', '0010_auto_20181109_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverrecord',
            name='source',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='источник'),
        ),
    ]
