# Generated by Django 2.0.5 on 2019-01-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogs', '0011_source_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverrecord',
            name='level',
            field=models.CharField(choices=[('INFO', 'INFO'), ('ERROR', 'ERROR'), ('DEBUG', 'DEBUG'), ('WARNING', 'WARNING')], default='INFO', max_length=8, verbose_name='важность'),
        ),
    ]
