# Generated by Django 2.0.9 on 2019-01-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogs', '0012_warning_loglevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverrecord',
            name='headquater',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='serverrecord',
            name='level',
            field=models.CharField(choices=[('INFO', 'INFO'), ('ERROR', 'ERROR'), ('DEBUG', 'DEBUG'), ('WARNING', 'WARNING')], db_index=True, default='INFO', max_length=8, verbose_name='важность'),
        ),
        migrations.AlterField(
            model_name='serverrecord',
            name='method',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='метод'),
        ),
        migrations.AlterField(
            model_name='serverrecord',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='источник'),
        ),
    ]
