# Generated by Django 2.0.3 on 2019-09-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applogs', '0013_auto_20190123_1149'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION count_estimate(query text) RETURNS INTEGER AS
                $func$
                DECLARE
                    rec   record;
                    ROWS  INTEGER;
                BEGIN
                    FOR rec IN EXECUTE 'EXPLAIN ' || query LOOP
                        ROWS := SUBSTRING(rec."QUERY PLAN" FROM ' rows=([[:digit:]]+)');
                        EXIT WHEN ROWS IS NOT NULL;
                    END LOOP;

                    RETURN ROWS;
                END
                $func$ LANGUAGE plpgsql;""",
            reverse_sql='DROP FUNCTION IF EXISTS count_estimate ();')
    ]
