# Generated by Django 2.2.2 on 2020-11-19 12:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogs', '0014_auto_20190916_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientrecord',
            options={'verbose_name': 'Системная ошибка', 'verbose_name_plural': 'Системные ошибки'},
        ),
        migrations.AddField(
            model_name='clientrecord',
            name='headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True, verbose_name='Заголовок запроса'),
        ),
        migrations.AddField(
            model_name='clientrecord',
            name='username',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Пользователь'),
        ),
    ]
