# Generated by Django 3.1.1 on 2020-10-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogs', '0014_auto_20190916_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverrecord',
            name='params',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='доп. информация'),
        ),
    ]
