# Generated by Django 3.1.6 on 2021-02-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogs', '0016_request_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrecord',
            name='headers',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Заголовок запроса'),
        ),
        migrations.AlterField(
            model_name='serverrecord',
            name='params',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='доп. информация'),
        ),
    ]
