# Generated by Django 3.2.25 on 2025-04-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogs', '0018_add_index_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverrecord',
            name='tags',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True, verbose_name='теги'),
        ),
    ]